src/main/java/com/example/SEENEMA/SeeNemaApplication.java
src/main/java/com/example/SEENEMA/config/SwaggerConfig.java
src/main/java/com/example/SEENEMA/post/view/controller/ViewPostController.java
src/main/java/com/example/SEENEMA/post/view/dto/ViewPostDto.java
src/main/java/com/example/SEENEMA/post/view/repository/ViewPostRepository.java
src/main/java/com/example/SEENEMA/post/view/service/ViewPostService.java
src/main/java/com/example/SEENEMA/post/view/service/ViewPostServiceImpl.java

- close #7 
<br>
-  상세화면·수정·삭제 API 로직 변경

시야 리뷰 API 수정

---

build.gradle
src/main/java/com/example/SEENEMA/mainPage/controller/MainPageController.java
src/main/java/com/example/SEENEMA/mainPage/domain/MainPage.java
src/main/java/com/example/SEENEMA/mainPage/dto/MainPageDto.java
src/main/java/com/example/SEENEMA/mainPage/service/MainPageService.java
src/main/java/com/example/SEENEMA/mainPage/service/MainPageServiceImpl.java

Web crawling

---

src/main/java/com/example/SEENEMA/mainPage/controller/MainPageController.java
src/main/java/com/example/SEENEMA/mainPage/dto/MainPageDto.java
src/main/java/com/example/SEENEMA/mainPage/service/MainPageService.java
src/main/java/com/example/SEENEMA/mainPage/service/MainPageServiceImpl.java

- #15 reasponse 타입 수정
- 뮤지컬 제목 추출 방식 수정
<br>
- reasponse 타입 : musicalRank, concertRank << return으로 수정
- 뮤지컬 제목 : 기존<> 안의 문자만 추출 --> '뮤지컬' 문자열 제외 모두 추출

#15 웹크롤링 reasponse 타입 변경 & 뮤지컬제목 수정

---

src/main/java/com/example/SEENEMA/mainPage/controller/MainPageController.java
src/main/java/com/example/SEENEMA/mainPage/dto/MainPageDto.java
src/main/java/com/example/SEENEMA/mainPage/service/MainPageService.java
src/main/java/com/example/SEENEMA/mainPage/service/MainPageServiceImpl.java

- #15 뮤지컬 이름 추출 함수 삭제
<br>
- 뮤지컬 <> 외에도 뮤지컬제목 양식이 여러 개 있어서 계속 오류가 생김 -> 삭제

#15 뮤지컬랭킹 뮤지컬이름 추출 함수 삭제

---

src/main/java/com/example/SEENEMA/theater/dto/TheaterDto.java

:adhesive_bandage: 공연장 조회 반환값 추가

---

src/main/java/com/example/SEENEMA/mainPage/service/MainPageServiceImpl.java

- close #31 
<br>
- 대부분의 콘서트는 공연 일시가 짧기 때문에 현재 공연 중인 콘서트의 양은 매우 적음 => 처음에는 공연 예정 콘서트만 크롤링
=> 공연 중인 콘서트도 필요할 것 같아서 sPlayType 2,3을 둘 다 가져오는 걸로 수정
- cast, detailUrl 가져오는 코드 수정

✨ 출연진, 상세 url 크롤링 코드 수정 + 공연 중/예정 콘서트로 수정

---

src/main/java/com/example/SEENEMA/mainPage/service/MainPageServiceImpl.java

:bug: 공연 랭킹 url 수정

---

src/main/java/com/example/SEENEMA/post/view/controller/ViewPostController.java
src/main/java/com/example/SEENEMA/post/view/repository/ViewPostRepository.java
src/main/java/com/example/SEENEMA/post/view/service/ViewPostService.java
src/main/java/com/example/SEENEMA/post/view/service/ViewPostServiceImpl.java

- #38 
<br>
- 상세화면/수정/삭제 url에 title 파라미터 삭제

:bug: 시야 리뷰 url 수정

---

src/main/java/com/example/SEENEMA/post/view/dto/ViewPostDto.java

- closes #42 
- 
<br>
- 상세화면 dto에 viewNo 추가

🐛 상세화면 dto에 viewNo 추가

---

src/main/java/com/example/SEENEMA/post/view/dto/ViewPostDto.java

- #42 
<br>
- 목록 dto에 viewNo 추가

:bug: 시야 리뷰 목록 dto 수정

---

src/main/java/com/example/SEENEMA/mainPage/dto/PlayDto.java
src/main/java/com/example/SEENEMA/mainPage/service/MainPageServiceImpl.java

- #31 
<br>
- 공연 크롤링 목록에 date까지 나타나게 수정

:sparkles: 뮤지컬/콘서트 목록에 일시 추가

---

src/main/java/com/example/SEENEMA/config/WebSecurityConfig.java
src/main/java/com/example/SEENEMA/mainPage/controller/MainPageController.java
src/main/java/com/example/SEENEMA/user/controller/UserController.java

- #27 로그인 기능
<br>
- 아이디 중복 확인 방법 수정
- api/login -> api/user/login 수정

:sparkles: #27 아이디 중복확인 방법 수정 &  api  수정

---

src/main/java/com/example/SEENEMA/mainPage/dto/PlayDto.java
src/main/java/com/example/SEENEMA/mainPage/service/MainPageServiceImpl.java

:bug: 공연 dto에 no 추가

---

build.gradle
src/main/java/com/example/SEENEMA/config/WebSecurityConfig.java
src/main/java/com/example/SEENEMA/mainPage/service/MainPageServiceImpl.java
src/main/java/com/example/SEENEMA/oauth/attribute/OAuthAttributes.java
src/main/java/com/example/SEENEMA/oauth/controller/OAuthController.java
src/main/java/com/example/SEENEMA/oauth/domain/Member.java
src/main/java/com/example/SEENEMA/oauth/dto/MemberDto.java
src/main/java/com/example/SEENEMA/oauth/repository/MemberRepository.java
src/main/java/com/example/SEENEMA/oauth/service/OAuthService.java
src/main/java/com/example/SEENEMA/test/controller/AuthController.java
src/main/java/com/example/SEENEMA/user/domain/PrincipalDetails.java
src/main/java/com/example/SEENEMA/user/domain/User.java
src/main/java/com/example/SEENEMA/user/dto/GoogleUserInfo.java
src/main/java/com/example/SEENEMA/user/dto/KakaoUserInfo.java
src/main/java/com/example/SEENEMA/user/dto/OAuth2UserInfo.java
src/main/java/com/example/SEENEMA/user/repository/UserRepository.java
src/main/java/com/example/SEENEMA/user/service/CustomUserDetailService.java
src/main/java/com/example/SEENEMA/user/service/PrincipalDetailsService.java
src/main/java/com/example/SEENEMA/user/service/UserService.java
src/main/java/com/example/SEENEMA/user/service/UserServiceImpl.java

- #49 콘서트 랭킹 수정
<br>
- url  수정
-  rank==10 -> rank>=10 으로 수정

공연 크롤링 콘서트 랭킹 수정

---

src/main/java/com/example/SEENEMA/config/WebSecurityConfig.java
src/main/java/com/example/SEENEMA/user/controller/UserController.java

- #27
- 
<br>
- 가입되지 않은 아이디, 잘못된 비밀번호 입력 시 서버 오류 내보내기 -> String으로 오류임 나타내기

:sparkles: #27 아이디, 비밀번호 틀린경우

---

src/main/java/com/example/SEENEMA/post/view/controller/ViewPostController.java

:rocket: 배포 오류 테스트

---

src/main/java/com/example/SEENEMA/post/theater/dto/TheaterPostDto.java
src/main/java/com/example/SEENEMA/post/view/dto/ViewPostDto.java

:bug: 게시물 수정 오류

---

src/main/java/com/example/SEENEMA/post/view/domain/ViewPost.java
src/main/java/com/example/SEENEMA/post/view/dto/ViewPostDto.java
src/main/java/com/example/SEENEMA/post/view/service/ViewPostServiceImpl.java

- #37 
<br>
- 시야리뷰 작성/수정 시 Request로 별점 4가지 추가로 받음
- 상세화면 Response에 별점 4가지 추가
- search 시 viewListResponse 에는 viewScore만 추가로 보여줌

시야리뷰 별점 기능 추가

---

src/main/java/com/example/SEENEMA/post/theater/controller/TheaterPostController.java

- #72 
<br>
- 토큰 유효성 검사 시 에러 메세지 상세화

:sparkles: #72 에러 메세지 상세화

---

src/main/java/com/example/SEENEMA/mainPage/dto/MainPageDto.java
src/main/java/com/example/SEENEMA/mainPage/service/MainPageServiceImpl.java

- closes #78 
<br>
- 크롤링에 이미지 url 추가

:sparkles:  공연 랭킹 이미지 추가

---

src/main/java/com/example/SEENEMA/post/view/controller/SeatController.java
src/main/java/com/example/SEENEMA/post/view/controller/ViewPostController.java
src/main/java/com/example/SEENEMA/post/view/domain/Seat.java
src/main/java/com/example/SEENEMA/post/view/domain/SeatHeart.java
src/main/java/com/example/SEENEMA/post/view/domain/SeatViewPost.java
src/main/java/com/example/SEENEMA/post/view/dto/SeatDto.java
src/main/java/com/example/SEENEMA/post/view/dto/ViewPostDto.java
src/main/java/com/example/SEENEMA/post/view/repository/SeatHeartRepository.java
src/main/java/com/example/SEENEMA/post/view/repository/SeatRepository.java
src/main/java/com/example/SEENEMA/post/view/repository/SeatViewPostRepository.java
src/main/java/com/example/SEENEMA/post/view/service/SeatService.java

- #58 
<br>
- 테스트용 아르코예술극장 소극장 db 추가
- x,y좌표별로 좌석 정보 넘겨주기

✨좌석 매핑 테스트

---

src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/ArcoController.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/ArcoService.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/repository/ArcoPostRepository.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/repository/ArcoRepository.java
src/main/java/com/example/SEENEMA/domain/theater/controller/TheaterController.java
src/main/java/com/example/SEENEMA/domain/theater/dto/TheaterDto.java
src/main/java/com/example/SEENEMA/domain/theater/service/TheaterService.java
src/main/java/com/example/SEENEMA/domain/theater/service/TheaterServiceImpl.java

- #58 
- 
<br>
-  좌석 페이지의 공연장 목록/ 공연장 조회/ 좌석 조회/ 리뷰 등록/ 리뷰 조회 기능

✨아르코 예술극장 좌석 등록+조회 완성

---

src/main/java/com/example/SEENEMA/domain/seat/SeatController.java
src/main/java/com/example/SEENEMA/domain/seat/SeatDto.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/ArcoService.java

:sparkles:  좌석 url if문 처리

---

src/main/java/com/example/SEENEMA/domain/seat/SeatController.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/ArcoService.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/domain/ArcoSeat.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/repository/ArcoRepository.java

:sparkles:  z좌표 추가(floor)

---

src/main/java/com/example/SEENEMA/domain/seat/SeatController.java
src/main/java/com/example/SEENEMA/domain/seat/SeatDto.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/ArcoService.java

:sparkles: seatDto수정/좌표 수정

---

src/main/java/com/example/SEENEMA/domain/seat/SeatController.java
src/main/java/com/example/SEENEMA/domain/seat/SeatDto.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/ArcoService.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/domain/ArcoHeart.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/domain/ArcoPost.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/repository/ArcoHeartRepository.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/repository/ArcoPostRepository.java

✨ 아르코 예술극장 완료

---

src/main/java/com/example/SEENEMA/domain/seat/SeatController.java
src/main/java/com/example/SEENEMA/domain/seat/SeatDto.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/ArcoService.java

- #58
<br>
- 공연장별 좌석 평균 목록 => 좌석 색 구별 위해서

:sparkles:  공연장별 좌석 평균 목록

---

src/main/java/com/example/SEENEMA/domain/seat/SeatDto.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/ArcoService.java

- #58 
- 
<br>
- detailResponse 삭제 => addResponse로 통합

:sparkles: 연동에 필요한 정보 수정

---

src/main/java/com/example/SEENEMA/domain/seat/SeatController.java
src/main/java/com/example/SEENEMA/domain/seat/SeatDto.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/ArcoService.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareShinhan/ShinhanService.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareShinhan/domain/ShinhanPost.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareShinhan/repository/ShinhanHeartRepository.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareShinhan/repository/ShinhanPostRepository.java

- #58
- 
<br>
- 블루스퀘어 신한카드홀 API 모두 완료
- 오류 없음

블루스퀘어 신한카드홀

---

src/main/java/com/example/SEENEMA/domain/seat/SeatController.java
src/main/java/com/example/SEENEMA/domain/seat/SeatDto.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareMasterCard/MastercardService.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareMasterCard/domain/MastercardPost.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareMasterCard/domain/MastercardSeat.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareMasterCard/repository/MastercardPostRepository.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareMasterCard/repository/MastercardRepository.java

- #58
<br>
-블루 스퀘어 마스터 카드홀 완료 + DB 좌석 생성 완료

블루스퀘어 마스터카드홀

---

src/main/java/com/example/SEENEMA/domain/seat/SeatController.java
src/main/java/com/example/SEENEMA/domain/seat/SeatDto.java
src/main/java/com/example/SEENEMA/domain/seat/chungmu/ChungmuService.java
src/main/java/com/example/SEENEMA/domain/seat/chungmu/domain/ChungmuPost.java
src/main/java/com/example/SEENEMA/domain/seat/chungmu/domain/ChungmuSeat.java
src/main/java/com/example/SEENEMA/domain/seat/chungmu/repository/ChungmuPostRepository.java
src/main/java/com/example/SEENEMA/domain/seat/chungmu/repository/ChungmuRepository.java

:sparkles: 충무아트센터 대극장 완료

---

src/main/java/com/example/SEENEMA/domain/seat/SeatController.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/domain/ArcoSeat.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareMasterCard/domain/MastercardSeat.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareMasterCard/repository/MastercardPostRepository.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareShinhan/domain/ShinhanSeat.java
src/main/java/com/example/SEENEMA/domain/seat/chungmu/domain/ChungmuSeat.java
src/main/java/com/example/SEENEMA/domain/user/controller/UserController.java
src/main/java/com/example/SEENEMA/domain/user/dto/MyPageDto.java
src/main/java/com/example/SEENEMA/domain/user/service/MyPageService.java
src/main/java/com/example/SEENEMA/domain/user/service/MyPageServiceImpl.java

- #58 
- 
<br>
- 내가 작성한 좌석후기 게시글
- DB에 (x,y,z) 정보가 없는 좌석 위치에 게시글을 post 할 때, insert하기

좌석없는 좌석 게시글POST

---

src/main/java/com/example/SEENEMA/domain/seat/SeatController.java

- #58
- 
<br>
- 좌석없는 좌표 GET할 때 좌석 만들기

좌석없는 좌석 게시글 GET

---

src/main/java/com/example/SEENEMA/domain/mainPage/repository/ConcertRepository.java
src/main/java/com/example/SEENEMA/domain/mainPage/repository/MusicalRepository.java
src/main/java/com/example/SEENEMA/domain/user/controller/UserFavoriteController.java
src/main/java/com/example/SEENEMA/domain/user/domain/UserFavorite.java
src/main/java/com/example/SEENEMA/domain/user/dto/UserFavoriteDto.java
src/main/java/com/example/SEENEMA/domain/user/service/UserFavoriteService.java

:sparkles:  배우, 장르별 공연 추천 기능

---

src/main/java/com/example/SEENEMA/domain/user/dto/UserFavoriteDto.java
src/main/java/com/example/SEENEMA/domain/user/repository/UserFavoriteRepository.java
src/main/java/com/example/SEENEMA/domain/user/service/UserFavoriteService.java

✨ 추천 기능 완료

---

src/main/java/com/example/SEENEMA/domain/seat/SeatController.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/ArcoService.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareMasterCard/MastercardService.java
src/main/java/com/example/SEENEMA/domain/seat/blueSquareShinhan/ShinhanService.java
src/main/java/com/example/SEENEMA/domain/seat/chungmu/ChungmuService.java

✨ 좌석 리뷰 조회 시 리워드 차감

---

src/main/java/com/example/SEENEMA/domain/mainPage/controller/MainPageController.java
src/main/java/com/example/SEENEMA/domain/mainPage/service/MainPageServiceImpl.java

뮤지컬, 콘서트 이미지 url 변경

---

src/main/java/com/example/SEENEMA/domain/seat/SeatController.java
src/main/java/com/example/SEENEMA/domain/seat/arcoTheater/ArcoService.java
src/main/java/com/example/SEENEMA/domain/user/domain/Reward.java

좌석별 게시물 조회 시 10점 차감
- 비로그인 -> should_login
- 잔여 포인트 10점미만 -> not_enough_point
시야리뷰 상세화면 조회 시 
5점 차감
- 비로그인 -> should_login
- 잔여 포인트 5점 미만 -> not_enough_point
회원가입 UserController
- Reward 생성 - 500L 기본

좌석별 게시물 조회 시 10점 차감, 시야리뷰 상세화면 조회시 5점 차잠, 회원가입 시 500점 부여

---

src/main/java/com/example/SEENEMA/domain/mainPage/controller/MainPageController.java
src/main/java/com/example/SEENEMA/domain/mainPage/domain/ConcertRanking.java
src/main/java/com/example/SEENEMA/domain/mainPage/domain/MusicalRanking.java
src/main/java/com/example/SEENEMA/domain/mainPage/dto/MainPageDto.java
src/main/java/com/example/SEENEMA/domain/mainPage/repository/ConcertRankingRepository.java
src/main/java/com/example/SEENEMA/domain/mainPage/repository/ConcertRepository.java
src/main/java/com/example/SEENEMA/domain/mainPage/repository/MusicalRankingRepository.java
src/main/java/com/example/SEENEMA/domain/mainPage/repository/MusicalRepository.java
src/main/java/com/example/SEENEMA/domain/mainPage/service/MainPageService.java
src/main/java/com/example/SEENEMA/domain/mainPage/service/MainPageServiceImpl.java
src/main/java/com/example/SEENEMA/domain/seat/TicketController.java

✨ 공연 랭킹 - 상세화면 연결

---

src/main/java/com/example/SEENEMA/domain/mainPage/controller/MainPageController.java
src/main/java/com/example/SEENEMA/domain/mainPage/domain/ConcertRanking.java
src/main/java/com/example/SEENEMA/domain/mainPage/domain/MusicalRanking.java
src/main/java/com/example/SEENEMA/domain/mainPage/dto/MainPageDto.java
src/main/java/com/example/SEENEMA/domain/mainPage/dto/PlayDto.java
src/main/java/com/example/SEENEMA/domain/mainPage/repository/ConcertRepository.java
src/main/java/com/example/SEENEMA/domain/mainPage/service/MainPageService.java
src/main/java/com/example/SEENEMA/domain/mainPage/service/MainPageServiceImpl.java
src/main/java/com/example/SEENEMA/domain/seat/SeatController.java

Cast recommendation

---

src/main/java/com/example/SEENEMA/domain/mainPage/controller/MainPageController.java
src/main/java/com/example/SEENEMA/domain/mainPage/repository/ConcertRepository.java
src/main/java/com/example/SEENEMA/domain/mainPage/service/MainPageServiceImpl.java
src/main/java/com/example/SEENEMA/domain/theater/domain/Theater.java
src/main/java/com/example/SEENEMA/domain/theater/dto/TheaterDto.java
src/main/java/com/example/SEENEMA/domain/user/controller/RecommendationController.java
src/main/java/com/example/SEENEMA/domain/user/domain/UserHistory.java
src/main/java/com/example/SEENEMA/domain/user/dto/UserHistoryDto.java
src/main/java/com/example/SEENEMA/domain/user/repository/UserHistoryRepository.java
src/main/java/com/example/SEENEMA/domain/user/repository/UserRepository.java
src/main/java/com/example/SEENEMA/domain/user/service/UserHistoryService.java

:sparkles: 공연장 위도,경도 추가

---

src/main/java/com/example/SEENEMA/domain/mainPage/controller/MainPageController.java
src/main/java/com/example/SEENEMA/domain/mainPage/domain/ConcertRanking.java
src/main/java/com/example/SEENEMA/domain/mainPage/domain/MusicalRanking.java
src/main/java/com/example/SEENEMA/domain/mainPage/dto/MainPageDto.java
src/main/java/com/example/SEENEMA/domain/mainPage/service/MainPageServiceImpl.java

- #126 인터파크 .... 
<br>
- 컨트롤러에서 service.getConcertRankings( ), service.getMusicalRankings( ) 호출 부분 서비스 부분 수정 
- 랭크 업다운 기능 추가 대비 컬럼 추가 ( domain, dto )
private int upDown;     // 1 : up , 0 : down
private int range;      // updown 폭?
// (upDown, range) : (1,0) 순위변동 X
//                 : (0,0) new

🐛  랭킹 오류 수정 !

---

src/main/java/com/example/SEENEMA/domain/mainPage/domain/Concert.java
src/main/java/com/example/SEENEMA/domain/mainPage/domain/Musical.java
src/main/java/com/example/SEENEMA/domain/mainPage/dto/PlayDto.java
src/main/java/com/example/SEENEMA/domain/mainPage/service/MainPageServiceImpl.java
src/main/java/com/example/SEENEMA/domain/theater/repository/TheaterRepository.java

:sparkles:  공연-공연장 연결

---

src/main/java/com/example/SEENEMA/domain/mainPage/controller/MainPageController.java
src/main/java/com/example/SEENEMA/domain/mainPage/service/MainPageServiceImpl.java

- #128
<br>
- String img 의 e.select("div") << 에 div class name 추가하여 이미지 div 명시

:bug:  #128 랭킹 이미지 오류 수정

---

src/main/java/com/example/SEENEMA/domain/mainPage/dto/PlayDto.java
src/main/java/com/example/SEENEMA/domain/mainPage/service/MainPageServiceImpl.java
src/main/java/com/example/SEENEMA/domain/theater/domain/Theater.java
src/main/java/com/example/SEENEMA/domain/theater/domain/TheaterImage.java
src/main/java/com/example/SEENEMA/domain/theater/dto/TheaterDto.java
src/main/java/com/example/SEENEMA/domain/theater/repository/TheaterImageRepository.java
src/main/java/com/example/SEENEMA/domain/theater/service/TheaterServiceImpl.java
src/main/java/com/example/SEENEMA/global/config/WebConfig.java

- #134 
- 
<br>
- 공연장 상세정보 추가 (오시는 길, 주차 안내)

:sparkles: #134 공연장 상세정보 추가-12까지

---

src/main/java/com/example/SEENEMA/global/config/WebConfig.java

- #Issue 번호 + 내용 작성
- 
<br>
- 내용 작성

:rocket: config 수정

---

src/main/java/com/example/SEENEMA/domain/user/controller/RecommendationController.java
src/main/java/com/example/SEENEMA/domain/user/service/UserHistoryService.java

:sparkles: 공연 추천 (랜덤 적용)
